name: Rainbond Docs GitHub Actions
on:
  push:
    branches:    
      - 'main'
jobs:
  rainbond-docs-build:
    name: build rainbond docs image and push image to dockerhub
    runs-on: ubuntu-20.04
    steps:
      - name: clone rainbond-docs repo
        uses: actions/checkout@main

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          key: cache-node-modules
          path: /node_modules

      - name: build and push Docker image
        env:
          RAINBOND_SECRET: ${{ secrets.RAINBOND_SECRET }}
          RAINBOND_API: ${{ secrets.RAINBOND_API }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOMESTIC_USERNAME: ${{ secrets.DOMESTIC_USERNAME }}
          DOMESTIC_PASSWORD: ${{ secrets.DOMESTIC_PASSWORD }}
          VERSION: ${{ env.VERSION }}
        run: ./release.sh